name: Rajat Vikram Singh
author: Rajat Vikram Singh
url: "http://rajatvikramsingh.github.io"
title: Rajat Vikram Singh
tagline: Personal Website

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: null
