name: Rajat Vikram Singh
author: Rajat Vikram Singh
url: "http://rajatvikramsingh.github.io"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: null

navigation:
    - title: home
      link: /
    - title: projects
      link: /projects.html
    - title: resume
      link: /resume/resume.pdf
    - title: contact
      link: /contact.html
#    - title: etc
#      link: /misc.html
